services:

    mjml:
        alias: notfloran_mjml.mjml

    notfloran_mjml.mjml:
        class: NotFloran\MjmlBundle\Mjml
        arguments:
            - "%notfloran_mjml.bin%"
            - "%notfloran_mjml.mimify%"

    notfloran_mjml.twig_extension:
        class: NotFloran\MjmlBundle\Twig\Extension
        arguments:
            - "@notfloran_mjml.mjml"
        tags:
            - { name: twig.extension }