name: "Coding Standard"

on:
    pull_request: ~
    push:
        branches:
            - master

env:
    fail-fast: true

jobs:
    cs-check:
        name: CS Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/files
                  key: ${{ runner.os }}

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4

            - name: Install Composer dependencies
              run: composer update

            - name: EasyCodingStandard
              run: composer cs-check
